# Generated by Django 4.0.5 on 2022-07-20 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='studentmessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=10)),
                ('gender', models.BooleanField(choices=[(1, '男'), (2, '女')])),
                ('age', models.IntegerField()),
                ('major', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'studentmessage',
            },
        ),
    ]
